/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubstitutesRouteImport } from './routes/substitutes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as IndexRouteImport } from './routes/index'

const SubstitutesRoute = SubstitutesRouteImport.update({
  id: '/substitutes',
  path: '/substitutes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/infrastructure': typeof InfrastructureRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/outreach': typeof OutreachRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/substitutes': typeof SubstitutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/infrastructure': typeof InfrastructureRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/outreach': typeof OutreachRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/substitutes': typeof SubstitutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/infrastructure': typeof InfrastructureRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/outreach': typeof OutreachRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/substitutes': typeof SubstitutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/attendance'
    | '/auth'
    | '/dashboard'
    | '/infrastructure'
    | '/inventory'
    | '/maintenance'
    | '/outreach'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/substitutes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissions'
    | '/attendance'
    | '/auth'
    | '/dashboard'
    | '/infrastructure'
    | '/inventory'
    | '/maintenance'
    | '/outreach'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/substitutes'
  id:
    | '__root__'
    | '/'
    | '/admissions'
    | '/attendance'
    | '/auth'
    | '/dashboard'
    | '/infrastructure'
    | '/inventory'
    | '/maintenance'
    | '/outreach'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/substitutes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  InfrastructureRoute: typeof InfrastructureRoute
  InventoryRoute: typeof InventoryRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OutreachRoute: typeof OutreachRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  SubstitutesRoute: typeof SubstitutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/substitutes': {
      id: '/substitutes'
      path: '/substitutes'
      fullPath: '/substitutes'
      preLoaderRoute: typeof SubstitutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsRoute: AdmissionsRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  InfrastructureRoute: InfrastructureRoute,
  InventoryRoute: InventoryRoute,
  MaintenanceRoute: MaintenanceRoute,
  OutreachRoute: OutreachRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  SubstitutesRoute: SubstitutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
